### ISSUE TITLE
Download youtube's video lectures

### ISSUE THREAD

**Issue by bitzge** [toto04/webeep-sync#107]
Hi, thank you very much for your work on webeep-sync!
Many students at Polimi's Ingegneria Informatica Online (IOL) would greatly benefit the automatic download of video lectures (hosted on youtube), is this possible to implement anytime soon? At the moment it only downloads mp3 and pdf files.
I would contribute however I don't have any skills on Electron/Typescript/React technologies.

Have a nice day

**Comment by toto04** [comment]
hi! glad you're liking it!
thanks a lot for the suggestion, as of right now, I think downloading videos from YouTube is a bit out of the scope of the app, this is designed to only sync files directly uploaded on webeep, whichever type of files they might be.
downloading something from YouTube is possible (using something like [youtube-dl-exec](https://www.npmjs.com/package/youtube-dl-exec)) but the urls must be consistently retrievable from webeep, and that would require writing ad-hoc download procedures for this specific case. also don't most professors upload video lectures on polimi's own website via Webex anyway?

just out of curiosity, can you give me the course name/ID so that I can look it up on webeep?

**Comment by bitzge** [comment]
Sorry for my delayed response, I'm going to answers to your questions:

> also don't most professors upload video lectures on polimi's own website via Webex anyway?
on IOL's course you have live lessons that are made with Webex platform (usually biweekly scheduled), however the most of the material's course is made from on-demand videos hosted on youtube with private links.

> just out of curiosity, can you give me the course name/ID so that I can look it up on webeep?
Sure! (I'm just cleaning professors' names from titles)
id: 7318 --> 082742 - ELETTROTECNICA
id: 12426 --> 085779 - ARCHITETTURA DEI CALCOLATORI E SISTEMI OPERATIVI

These are the typical standard voices on a course 
<img width="1015" alt="image" src="https://github.com/toto04/webeep-sync/assets/4791819/007f3767-4661-4bb2-bcc4-f5760709d4d2">

Inside lezioni you have this structure
<img width="882" alt="image" src="https://github.com/toto04/webeep-sync/assets/4791819/add3087e-58b3-449d-ab0b-f571b357a02c">

Inside each lesson you have one or multiple video pages embedding a youtube url
<img width="1556" alt="image" src="https://github.com/toto04/webeep-sync/assets/4791819/568f1bac-f4a8-4406-a505-80cc16ade8c5">

This is the piece where the link is contained (I obscured the youtube link)
<a class="ytp-title-link yt-uix-sessionlink" target="_blank" data-sessionlink="feature=player-title" tabindex="0" href="https://www.youtube.com/watch?v=******">Lezione 2 - Calcolatori a n livelli - I livelli nei moderni calcolatori</a>

If there's anything I can do, just tell me. It doesn't seem much work, do you? I'd like to make you a PR but at the moment I don't know where to put my hands on the codebase

**Comment by toto04** [comment]
It definitely seems like a lot of work tbh 😅
if you want to give it a shot you are more than welcome to tho!

I'll try to quickly explain what's going on and where you should look to understand a bit more, to begin inside the `src/modules` folder there are a bunch of classes that handle a bunch of different aspects of the app, you would be interested only in the `moodle` module that handles API calls and the `download` module that coordinates the sync procedure.

inside `moodle.ts` file you would be really interested in the `getFileInfos()` function that retrieves information about all files that should be downloaded inside of a course, here I excluded the "lesson" modname (that's how moodle calls the sort of types of posts idk) which appears to be the one in your screenshots. I don't remember exactly, but I think I excluded it bc probably the connected content was just the html page which in your case has the YouTube video embedded, you would need to somehow extract its video id.
