### ISSUE TITLE
-BUG- Spazio alla fine del nome della cartella

### ISSUE THREAD

**Issue by fede-mat** [toto04/webeep-sync#20]
Ciao vorrei segnalare che se sincronizzo una cartella dal nome 'Lab 1 ' ( con lo spazio alla fine) ed è impostata per essere salvata su One Drive lo spazio alla fine mi darà errore e farà si che venga rinominata 'Lab 1_'. Dal momento che i due nomi non corrispondono la cartella verrà riscaricata ridando vita allo stesso problema e si creerà così un ciclo infinito di rinomine e risincronizzazioni. 
È un po' macchinoso e non so se mi sono spiegato adeguatamente.

**Comment by toto04** [comment]
Grazie mille per la segnalazione!
Essenzialmente basterebbe impedire che le cartelle vengano rinominate con dei degli spazi all'inizio/fine se ho capito bene. 
Cercherò di riprodurre il bug e sarà fixato nella prossima versione minore.
