### ISSUE TITLE
Badly named file causes error

### ISSUE THREAD

**Issue by gubo97000** [toto04/webeep-sync#29]
A file named:
"Lesson 9.2 / 10 - Backend technology"
causes the software to create a corrupted folder (that shouldn't exist), or -based on permissions- just raises an error:
![image](https://user-images.githubusercontent.com/23000960/160904606-abdb1574-5970-4c6e-ae09-e3fdf43f9a43.png)

**Comment by toto04** [comment]
sorry if i get back to you just now 😅

I'm guessing the OS is windows, i swear the fs is so buggy, I'm guessing the problem has to do with the trailing space before the slash, which is TECHINCALLY a valid character for a folder name but at the same time file explorer doen't know hot to handle it.

This is actually closely related to #24 but I missed this specific case, won't be hard to fix, thank you for reporting!
