### ISSUE TITLE
Build fails on Linux with Nodejs > 16

### ISSUE THREAD

**Issue by darcros** [toto04/webeep-sync#37]
`yarn make` fails when using a Nodejs version greater than 16 on Linux.
I found that the problem can be fixed by setting this env variable: `NODE_OPTIONS=--openssl-legacy-provider`.

Tested on:
- Ubuntu 22.04.1 by running `yarn make --targets @electron-forge/maker-deb`
- Fedora 36 by running `yarn make --targets @electron-forge/maker-rpm`

Nodejs versions tested: (:heavy_check_mark: compiles, :x: needs flag to compile)
| |  Ubuntu | Fedora |
| --- | --- | --- |
| Nodejs v16.17.0 | :heavy_check_mark:  | :heavy_check_mark:  |
| Nodejs v17.6.0   | :x: | :x: |
| Nodejs v18.9.0   | :x: | :x: |

**Comment by toto04** [comment]
This is due to a conflict with the version of webpack currently in the package.json, I'll fix all the dependencies while upgrading electron version before next release

**Comment by toto04** [comment]
This should be fixed as of the [latest commit](https://github.com/toto04/webeep-sync/commit/b220ad60f459bc596dce1ff97322e85eb9f97e80)
Tested with node v16.15.0 and v18.10.0 on macOS on arm (this issue affected all OSs) and they both work without issues, please reopen the issue if this still persists on linux
