### ISSUE TITLE
Executable for Linux

### ISSUE THREAD

**Issue by luca-brambilla** [toto04/webeep-sync#60]
HI!

I am currently running the code with no problem, but with a slight inconvenience... I need to go to the folder and run in the terminal `yarn start`.
Is there a way I could run in as an executable or create a bash script that allows me to run it without passing through the terminal?

Cheers

**Comment by toto04** [comment]
Hi! There sure is! 

As per the [electron-forge documentation](https://www.electronforge.io/cli) you can create standalone packages of the app pretty easily.
You can either just ```package``` the app and install it manually yourself or ```make``` a full installer, I'll quickly explain the latter as it's the less hacky/finicky solution.

Assuming you are on a Debian-based distro like Ubuntu:
```sh
yarn make --targets="@electron-forge/maker-deb"
```
will create the ```.deb``` (you will need to have ```fakeroot``` installed with apt) which you'll find navigating inside the ```webeep-sync/out/make/``` folder.
You can then install it by using
```sh
dpkg -i filename.deb
```
where the filename varies with the current version and you processor type, should be something like ```webeep-sync_0.9.0_amd64.deb```.
Once installed with ```dpkg```, WeBeep Sync will be available as an app from the "Show Applications" tab in Ubuntu, and by using the command ```webeep-sync``` from anywhere in the terminal.

That being said, ```yarn start``` is a command just like any other, and the executable that electron-forge spits out is an executable like any other, so to using it in a bash script should be as easy as using anything else in a bash script lol.


_Please do keep in mind that while linux is technically supported, many features won't work as the implementation is not yet fully flashed out, so you might have to do some trial and error, in the (upcoming) full release I'll include a linux installer alongside the ones for Windows and macOS._

**Comment by luca-brambilla** [comment]
Thank you very much!

I tried using a bash script, but I wanted to add it to the Application menu and I wasn't able to figure it out.
Tbh I am not familiar with NodeJS, Yarn nor Electron :disappointed_relieved: 

I'm running Fedora on my machine and I had some problems trying to follow your proposed solution, but maybe I made it anyway.

TD;DR `yarn package` works, `yarn make --targets="@electron-forge/maker-rpm"` did not work for me.

I installed `fakeroot` with `dnf` and I tried `yarn make --targets="@electron-forge/maker-rpm"` but i got an error:
```
An unhandled rejection has occurred inside Forge:
Error: Cannot make for rpm, the following external binaries need to be installed: rpmbuild

Electron Forge was terminated. Location:
{}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I tried `yarn add @electron-forge/maker-rpm` and `npm install @electron-forge/maker-rpm` but it gave me security warnings.
I tried to fix them with `npm audit fix` and `npm audit fix --force`, as suggested, but I still got some warnings...
Reusing `yarn` gave me the same errors as before even at this point.

So I gave up and tried `yarn package` and I got the executable that I added manually to the Application menu. :smile:

**Comment by toto04** [comment]
What you were doing was actually right!
The error doesn't refer to a missing package or anything like that, it's an error from ```@electron-forge/maker-rpm``` which needs the actual ```rpmbuild``` binary in order to make the .rpm installer.
I'm not familiar with fedora, but I think it should be installed with something like
```sh
yum install rpm-build
```

(and by the way, ignore the security warnings, that is just npm rambling about vulnerabilities in certain packages, they are not relevant to the app functionality)

Anyway, glad you found a solution that works for you! And once more, just for the record, in future releases I'll provide both .deb and .rpm prebuilt installers, as they were already configured in the [forge config](https://github.com/toto04/webeep-sync/blob/main/forge.config.js) in #36
