### ISSUE TITLE
Problem downloading big sized file

### ISSUE THREAD

**Issue by GabThrap** [toto04/webeep-sync#81]
Webeep sync struggles downloading a 209.9 MB sized .mp4 file, it gets to avout 70%, then restarts a few times and then resets one last time and gives an unknown error

**Comment by toto04** [comment]
Hi thanks for reporting this!

That's an interesting one, I'm really not sure what could be causing this lol. I need to ask a couple of things to help me debug this:
1. First of all what OS are you on?
2. What version of WeBeep Sync are you running? I'm assuming `1.0.0` but just to be sure lol, you can find it at the bottom of the Settings page
3. Can you post a log file of when this issue has occurred? you can find log files in:
    - Windows: `%APPDATA%\WeBeep Sync\app_logs`
    - macOS: `~/Library/Application Support/WeBeep Sync/app_logs`
    - Linux: `~/.config/WeBeep Sync/app_logs`
4. (most usefully) can you tell me the ID of the course that contains that file (the number at the beginning of the course full name)? If I can enroll in it from WeBeep manually I can try to reproduce this bug on my machine

**Comment by GabThrap** [comment]
I'm on windows 10, I believe it's the latest release, and wBSync is on 1.0.0

[2023-01-21T15.53.30.log](https://github.com/toto04/webeep-sync/files/10472512/2023-01-21T15.53.30.log)

And the course is 093279 - FISICA TECNICA E MACCHINE (BARICCI ANDREA) [2022-23], though you will have to get accepted by the teacher.
