### ISSUE TITLE
Download ripetuto

### ISSUE THREAD

**Issue by PolimiGiovanniArriciati** [toto04/webeep-sync#88]
Ciao, ho un problema che mi scarica ogni volta che si avvia un sync gli stessi 13 file di un corso che però non cambiano. Non ho idea del perchè siano proprio quelli. Dimmi se ci sono info che ti possono aiutare a debuggare questa cosa.
Grazie.
Giovanni Arriciati

**Comment by mattiacolombomc** [comment]
Maybe you're running version ```1.0.0``` instead of[ the latest release](https://github.com/toto04/webeep-sync/releases/tag/v1.0.1)? I had the same issue, updating to the latest release fixed it. (See #84 )

**Comment by PolimiGiovanniArriciati** [comment]
No, sono alla 1.0.1

**Comment by toto04** [comment]
mhhh, sicuramente ha qualcosa a che vedere con #84, riusciresti a darmi il nome / id del corso in cui sono presenti questi 13 file che ti danno problemi?

**Comment by PolimiGiovanniArriciati** [comment]
è il corso 090950 - DISTRIBUTED SYSTEMS

**Comment by PolimiGiovanniArriciati** [comment]
Questi sono i file incriminati. Non so se possa servire
<img width="635" alt="Screenshot 2023-01-22 at 16 24 48" src="https://user-images.githubusercontent.com/100694500/213923960-9a9876f4-8a01-453e-9fde-26512a77715c.png">

**Comment by PolimiGiovanniArriciati** [comment]
Ho trovato il baco.
Su webeep sono iscritto al corso 21-22 e 22-23.
Ho chiamato le cartelle nello stesso modo.
Ho attivato la sincronizzazione per entrambi.
