### ISSUE TITLE
Notification button rendering issue

### ISSUE THREAD

**Issue by zibasPk** [toto04/webeep-sync#91]
Clicking on the notification button removes all'ui on the application leaving a blank page. v1.0.1 on windows 11 1920x1080 125%
![Screenshot (1)](https://user-images.githubusercontent.com/82605801/220849979-b883cbff-56f9-4955-8c61-fc8cd9220a7f.png)

**Comment by toto04** [comment]
fixed with release [1.0.2](https://github.com/toto04/webeep-sync/releases/tag/v1.0.2), thanks for the report!
