### ISSUE TITLE
[macOS]Redundant Notifications Issue: Webeep Sync Repeatedly Adding Itself to Login Items

### ISSUE THREAD

**Issue by mattiacolombomc** [toto04/webeep-sync#96]
Hello,

I've encountered an issue where Webeep Sync is continually adding itself to the login items, despite not being removed from the list. This seems to lead to a redundancy problem, with multiple unnecessary notifications appearing at each login.

This problem has occurred on multiple machines running on macOS 13.4 (22F66) and Webeep Sync v1.0.2.

Please find a screenshot of the repeated notifications below for your reference:
<img width="355" alt="CleanShot 2023-06-15 at 10 08 50@2x" src="https://github.com/toto04/webeep-sync/assets/55593934/f95c726b-7550-43aa-85b4-2b58dfcd15bc">

**Comment by mattiacolombomc** [comment]
Still happening, any chance you could investigate on this?

**Comment by toto04** [comment]
yep sorry, I forgot to check this out, I'll look into it as soon as I can, thank you!

**Comment by toto04** [comment]
please check the newly released version 1.0.3 and see if you can still reproduce it, if so reopen this issue! thanks for the report once again!
